baseurl = "/"
# languageCode = "ja"
# defaultContentLanguage = "ja"
hasCJKLanguage = true
title = "motoshira.net"
theme = "hello-friend"
showReadingTime = false

[languages]
  [languages.en]
    title = "motoshira.net"
    subtitle = "motoshira's web site"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = ""
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
    #   logoText = "motoshira.net"
    #   logoHomeLink = "/"
      path = "/icon_picture.png"
      alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "profile"
        name = "Profile"
        url = "/profile"